---

all:
  hosts:
    localhost:
      ansible_python_interpreter: python
      ansible_connection: local
  children:
    aws_ec2:
      vars:
        ansible_user: ec2-user
        provision_type: aws
  vars:
    openshift_public_hostname: "{{ cluster_name }}.{{ openshift_base_domain }}"
    cluster_name_verbose: "{{ openshift_public_hostname | replace('.', '-') }}"
    cluster_group_name: "{{ cluster_name_verbose | replace('-', '_') }}"
    keys_dir: "{{ playbook_dir }}/keys"
    ec2_key_name: "{{ cluster_name_verbose }}"
    ec2_key_file: "{{ keys_dir }}/{{ ec2_key_name }}.pem"
