---

- include_tasks: aws.yml
  when: provision_type == 'aws'

- name: Register host to RHSM and attach pool
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    pool_ids: "{{ rhsm_pool }}"
    consumer_name: "{{ rhsm_consumer_name | default(omit) }}"
    state: present
  become: yes

- name: Set Ansible version for required repos (default)
  set_fact: 
    ansible_repo_version: "2.4"

- name: Set Ansible version for required repos (OCP 3.11)
  set_fact: 
    ansible_repo_version: "2.6"
  when: (openshift_version | string) == "3.11"

- name: Enable required repositories
  rhsm_repository:
    name: "{{ openshift_repos }}"
    state: enabled
  retries: 3  # This seems to fail sometimes, so lets retry before failing everything
  register: openshift_enable_repos
  become: yes

- name: Disable non-required repositories
  rhsm_repository:
    name: "{{
      openshift_enable_repos.repositories |
      map(attribute='id') |
      difference(openshift_repos) }}"
    state: disabled
  retries: 3  # This seems to fail sometimes, so lets retry before failing everything
  become: yes
