---

- name: update nodes for Elasticsearch max_map_count
  copy:
    src: 99-elasticsearch.conf
    dest: /etc/sysctl.d/99-elasticsearch.conf
    owner: root
    group: root
    mode: 0644
  become: yes

- name: update max_map_count
  command: sysctl vm.max_map_count=262144
  become: yes
