---

- name: Find EC2 instances
  ec2_instance_facts:
    region: "{{ aws_region }}"
    filters:
      tag:OpenShiftClusterName: "{{ cluster_name }}"
      tag:OpenShiftClusterNameVerbose: "{{ cluster_name_verbose }}"
  register: ec2_find_instances

- name: Delete elastic IPs for instances
  ec2_eip:
    device_id: "{{ item.instance_id }}"
    region: "{{ aws_region }}"
    release_on_disassociation: yes
    state: absent
  with_items: "{{ ec2_find_instances.instances }}"

- name: Delete EC2 instances
  ec2_instance:
    region: "{{ aws_region }}"
    filters:
      tag:OpenShiftClusterName: "{{ cluster_name }}"
      tag:OpenShiftClusterNameVerbose: "{{ cluster_name_verbose }}"
    state: absent
