---

- name: Refresh inventory to update EC2 instances information
  meta: refresh_inventory

- name: Add host facts to OpenShift nodes
  add_host:
    name: "{{ item }}"
    ansible_host: "{{ hostvars[item].public_ip_address }}"
    ansible_ssh_private_key_file: "{{ ec2_key_file }}"
    rhsm_consumer_name: "{{ hostvars[item].tags.Name }}"
  with_items: "{{ groups.openshift_nodes | intersect(groups['openshift_cluster_' + cluster_group_name]) }}"
  changed_when: no

- name: Wait for nodes to boot
  wait_for:
    host: "{{ hostvars[item].ansible_host }}"
    port: 22
    search_regex: OpenSSH
  delegate_to: localhost
  with_items: "{{ groups.openshift_nodes | intersect(groups['openshift_cluster_' + cluster_group_name]) }}"
