---

- name: Create users
  command: htpasswd -b /etc/origin/master/htpasswd '{{ item.username }}' '{{ item.password }}'
  with_items: "{{ openshift_users }}"
  become: yes

- name: Create admin users
  command: oc adm policy add-cluster-role-to-user cluster-admin '{{ item.username }}'
  run_once: yes
  with_items: "{{ openshift_users }}"
  when: item.admin is defined and item.admin == True
